version: '3'

services:
  traefik:
    build: .
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    networks:
      - prometheus
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    external_links:
      - prometheus

networks:
 prometheus: 
   external:
     name: dockerprometheus_back-tier
